#!/bin/sh

addToPath() {
  new_entry="$1"

  case "$PATH" in
    # Don't add it to the path if it exists
    *$new_entry*) ;;

    # Add it to the path if it doesn't exist
    *) PATH="$new_entry:$PATH" ;;
  esac
}

DIR="$(dirname $(realpath "$0"))"

addToPath "${HOME}/.local/bin"
# addToPath "${HOME}/.node_modules/bin"
addToPath "/usr/local/bin"

# export npm_config_prefix="${HOME}/.node_modules"
export EDITOR="nvim"
export TERMINAL="kitty"
export VAULT_ADDR="https://vault.dev.cahcommtech.com"

export DOCKER_HOST_IP="localhost"
export JAVA_HOME="/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home"
# export M2_HOME=/path/to/maven/home
# export CASSANDRA_HOME=/path/to/cassandra/home
  
export S3_UNIQUE_PREFIX=com.cardinalhealth.fuse.s3.${USER}

addToPath "${JAVA_HOME}/bin"
# addToPath "$M2_HOME/bin"
# addToPath "$CASSANDRA_HOME/bin"
