# Default Source
source ~/.profile

# History
HISTFILE=~/.zsh_history
HIST_STAMPS="yyyy-mm-dd"
HISTSIZE=50000
SAVEHIST=50000

# Completion
autoload -Uz compinit
compinit
zstyle :compinstall filename "$HOME/.zshrc"

# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"

export NVM_NO_USE=true

ZSH_THEME="mcallaster"
plugins=(
  gitfast                  # Git integration (but faster)
  zsh-nvm
  zsh-autosuggestions      # Fish-like autosuggestions (https://github.com/zsh-users/zsh-autosuggestions)
  history-substring-search # Fish-like history substring search (https://github.com/zsh-users/zsh-history-substring-search)
)
source $ZSH/oh-my-zsh.sh

# Aliases
alias e="$EDITOR $argv"
alias ohmyzsh="$EDITOR ~/.oh-my-zsh"
alias reload="source $HOME/.zshrc"
alias zshconfig="$EDITOR ~/.zshrc"

alias mddc="cd ~/Git/mobius-deploy/mobius-integration-tests/mobius-integration-common/dc/"
alias adf="fly -t arrested-developers $argv"

alias java8="export JAVA_HOME='/Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home'"
alias java11="export JAVA_HOME='/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home'"

alias bastion="ssh bastion -t 'tmux new-session -A -s main'"

# Functions
function unzipall() {
  for file in *.zip
  do
    unzip -d "${file%.zip}" "$file"
  done
}

function portforward() {
  read "REMOTE_HOST?Remote host: "
  read "REMOTE_PORT?Remote port: "
  read "LOCAL_PORT?Local port: "
  echo "$REMOTE_HOST, $REMOTE_PORT, $LOCAL_PORT"
  ssh -f -N bastion -L "localhost:$LOCAL_PORT:$REMOTE_HOST:$REMOTE_PORT"
}

# VIM-like Keybindings
bindkey -v # Enable VI mode
bindkey '^?' backward-delete-char                  # Fix backspace after exiting normal mode
bindkey '^h' backward-delete-char                  # Fix ctrl+h after exiting normal mode
bindkey '^w' backward-kill-word                    # Vim-like ctrl+w word deletion
export KEYTIMEOUT=1 # Reduce delay of entering VI mode when pressing ESC

# History Substring Search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
